services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: backend-api
    ports:
      - "9000:9000"
      - "9001:9001"  # Puerto para WebSocket
    environment:
      HOST: 0.0.0.0
      PORT: 9000
      PYTHONUNBUFFERED: 1
      PYTHONPATH: /app
      SOCKETIO_ASYNC_MODE: asgi
      DB_API: http://smartpay-db-api:9002
      USER_SVC_URL: http://smartpay-db-api:9002
      REDIRECT_URI: https://smartpay-oficial.com:9000/api/v1/google/auth/callback
      CLIENT_SECRET: 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
      CLIENT_ID: 631597337466-dt7qitq7tg2022rhje5ib5sk0eua6t79.apps.googleusercontent.com
      # Configuración de correo electrónico
      SMTP_SERVER: smtp.gmail.com
      SMTP_PORT: 587
      SMTP_USERNAME: smartpay.noreply@gmail.com
      # Contraseña de aplicación de Google - con espacios como la mostró Google
      SMTP_PASSWORD: 'jgiz oqck snoj icwz'
      EMAIL_FROM: smartpay.noreply@gmail.com
      RESET_PASSWORD_BASE_URL: https://smartpay-oficial.com/reset-password

    volumes:
      - ..:/app
      - ./logs:/app/logs
      # - /etc/ssl/smartpay:/etc/ssl/smartpay:ro  # Comentado temporalmente
      # Montar Docker socket para Docker-in-Docker
      - /var/run/docker.sock:/var/run/docker.sock
      # Montar directorio padre para acceso a deployments
      - /home/danielamg/Escritorio/trabajo/olimpo/smart-pay:/host/smart-pay
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # Comando sin SSL para desarrollo
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "9000"]
    sysctls:
      - net.core.somaxconn=65535
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    networks:
      - smartpay

  # Servicio de base de datos para desarrollo
  smartpay-db:
    image: postgres:12
    container_name: smartpay-db-dev
    ports:
      - "5436:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: smartpay
    volumes:
      - smartpay-db-dev:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - smartpay
      
  # Servicio de API de base de datos para desarrollo
  smartpay-db-api:
    build:
      context: ../../db-smartpay
      dockerfile: docker/Dockerfile
    container_name: smartpay-db-api-dev
    ports:
      - "9002:9002"
    environment:
      - PYTHONUNBUFFERED=1
      - WEB_APP_VERSION=0.1.0
      - WEP_APP_TITLE=smartpay-db
      - WEP_APP_DESCRIPTION=Database service for SmartPay
      - ENVIRONMENT=dev
      - POSTGRES_DATABASE_URL=postgres://postgres:postgres@smartpay-db:5432/smartpay
      - DEFAULT_DATA=False
      - PYTHONPATH=/usr/src/app
    volumes:
      - ../../db-smartpay:/usr/src/app
    command: ["python", "-m", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "9002", "--reload"]
    depends_on:
      smartpay-db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - smartpay

networks:
  smartpay:
    name: smartpay
    driver: bridge

volumes:
  smartpay-db-dev:
